### ISSUE TITLE
ReDial Recommender Results

### ISSUE THREAD

**Issue by alemartina23** [RUCAIBox/CRSLab#69]
Hi! I'm trying to reproduce the baseline results observed in the paper "Towards Unified Conversational Recommender Systems via
Knowledge-Enhanced Prompt Learning" available here https://arxiv.org/pdf/2206.09363.pdf

Using the configuration in config/crs/redial/redial.yaml for ReDial I'm getting the following results on the recommendation task:

- With early stop (8 epochs): {"hit@1": 0.0002498, "hit@10": 0.009493, "hit@50": 0.08818, "mrr@1": 0.0002498, "mrr@10": 0.002024, "mrr@50": 0.005041, "ndcg@1": 0.0002498, "ndcg@10": 0.003739, "ndcg@50": 0.02005, "rec_loss": 10.3}
- Without early stop (50 epochs): {"hit@1": 0, "hit@10": 0.0002498, "hit@50": 0.0602, "mrr@1": 0, "mrr@10": 3.123e-05, "mrr@50": 0.00158, "ndcg@1": 0, "ndcg@10": 7.881e-05, "ndcg@50": 0.01134, "rec_loss": 10.29}

I was wondering if someone can provide the instructions for getting results similar to those shown in the paper I mentioned.

**Comment by lengshuiyu332** [comment]
As previously mentioned by @wangxieric, there is a performance degradation during training due to a lack of pre-training (because it was originally designed for the specific dataset `ReDial` and can not be applied to all datasets). If you want to reproduce closer performance, you could try `batch_size: 128` and `lr: !!float 1e-4` in the `rec` part of the file `config/crs/redial/redial.yaml` instead of the default setting.

This is the result using the above parameters:
{hit@1: 0.01262  hit@10: 0.06246  hit@50: 0.1947  mrr@1: 0.01262  mrr@10: 0.02364  mrr@50: 0.02948  ndcg@1: 0.01262  ndcg@10: 0.0326  ndcg@50: 0.06119  rec_loss: 20.52}(14 epochs)

**Comment by wangxieric** [comment]
The above solution for the ReDial model does not enable stable performance. The results can get close to the given results as above, but also frequently end up with much lower performance.
